### ISSUE TITLE
Handle invalid checkpoints with level < 0

### ISSUE THREAD

**Issue by jacodg** [ibissource/ladybug-frontend#243]
When a report has one or more invalid checkpoints with level < 0 the report doesn't open. The old GUI couldn't open them either and gave an exception, this has been solved:

https://github.com/ibissource/ibis-ladybug/commit/014a9d01c9e6b9bec1b4ae7b458cd2e8e438a585
https://github.com/ibissource/ibis-ladybug/commit/3b935272133123c3a98890fd398cb267e98e4246

It is with the proof of migration storage that some invalid reports are currently generated. @lenardvandermaas  is currently looking into this but is would still be nice when the new GUI can also handle these invalid reports/checkpoints.

**Comment by celmoussaoui** [comment]
Create a checkpoint which has a level of -1 to reproduce
