### ISSUE TITLE
On view switch: clear table before doing request for new data

### ISSUE THREAD

**Issue by jacodg** [ibissource/ladybug-frontend#257]
When switching view using the dropdown: When it takes a long time to retrieve the data for the table of the new view it gives the impression that the Ladybug isn't working correctly as you see the data from the old view with the columns of the new view (until the data for the new view is returned).

To reproduce this add the following to the end of the buildMetadataQuery() method in the ProofOfMigrationStorage.java and switch to the Proof of migration view in the GUI:

		try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

**Comment by philipsens** [comment]
Fixed in f6cf05abf5361a43b745f2c7148055b8e5f4534b
