### ISSUE TITLE
Filter not reset or search value not kept visible when switching view

### ISSUE THREAD

**Issue by jacodg** [ibissource/ladybug-frontend#259]
When for example in the test webapp you:

- Click the filter button and add a value to the name filter to make only one row visible
- Switch to the Proof of migration view and then back to the original view

Then there is still only one row visible but the search value isn't visible in the name filter text field anymore

**Comment by celmoussaoui** [comment]
We would rather have that the filter is still active. If this is not possible, then having it reset is also fine.

**Comment by celmoussaoui** [comment]
I have opted for clearing the filter
