### ISSUE TITLE
Implement possibility to delete report in debug tab

### ISSUE THREAD

**Issue by jacodg** [ibissource/ladybug-frontend#268]
In the old GUI it is possible to delete reports when the debug storage not only implements LogStorage but also CrudStorage. See the code of the old GUI:

https://github.com/ibissource/ibis-ladybug/blob/v2.2/src/main/java/nl/nn/testtool/echo2/reports/ReportComponent.java#L343

This is used by Tibet2.

It can be tested with the test webapp that is using the memory storage by default (which implements both LogStorage and CrudStorage)

**Comment by celmoussaoui** [comment]
Make an API call that checks if the storage is a Crudstorage, if so, you can add the delete button and consequently delete reports from debug tab.
