### ISSUE TITLE
Run Cypress tests also for browsers Firefox and Edge

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/ladybug-frontend#30]

**Comment by mhdirkse** [comment]
There is a bug in Cypress related to Firefox: https://github.com/cypress-io/cypress/issues/17896. When you download files using Firefox on Windows, then the downloads do not appear in the folder configured in Cypress.

**Comment by mhdirkse** [comment]
Browser Edge is not supported in Linux:
![image](https://user-images.githubusercontent.com/6784732/155977061-bccf0146-5198-4b98-b78b-eea52591a8c7.png)

**Comment by bryding** [comment]
This is still happening for me. Windows 11, Firefox 100, Cypress 9.6.0

**Comment by mhdirkse** [comment]
Thanks, @anthonysessa and @bryding for visiting our project and commenting on this issue. We closed the issue because we cannot proceed with this issue within our team. If you can fix Cypress for downloading with Firefox, we are happy to reopen this issue.
